# Generated by Django 4.2.5 on 2023-10-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='password',
            new_name='contraseña',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='usuario',
        ),
    ]
