# Generated by Django 4.2.3 on 2023-10-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default=1, upload_to='usuario/'),
            preserve_default=False,
        ),
    ]
