# Generated by Django 4.2.3 on 2023-10-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
