# Generated by Django 4.2.6 on 2023-10-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='imagen_default.png', upload_to='producto'),
        ),
    ]
