# Generated by Django 4.2.3 on 2023-10-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_servicio_imagen_alter_producto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='image',
            new_name='imagen',
        ),
    ]
