# Generated by Django 4.2.3 on 2023-10-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_image_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='usuario/default.png', upload_to='usuario/'),
        ),
    ]
